In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]

In [10]:
import pandas as pd
data={"name":["mikey","hemanthreddy","abhinav"],"id":[47,46,10]}
df=pd.DataFrame(data)
print(df)

           name  id
0         mikey  47
1  hemanthreddy  46
2       abhinav  10

In [37]:
import numpy as np
a=np.arange(1,31)
print(a.reshape(1,2,5,3))
print(a.ndim)
print(a.shape)
print(a.mean())
print(np.median(a))

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]
   [13 14 15]]

  [[16 17 18]
   [19 20 21]
   [22 23 24]
   [25 26 27]
   [28 29 30]]]]
1
(30,)
15.5
15.5

In [35]:
with open("encapsulation.py",'r') as f:
    print(f.read())

class ATM():
    def __init__(self,name,pin,balance):
        self.name=name
        self.__pin=pin
        self._balance=balance
    def check_balance(self):
        print("here's your current balance:",self._balance)
    def verify_pin(self,pin):
        return pin==self.__pin
    def deposit(self,amount):
        self.amount=amount
        if amount>0:
            self._balance+=amount
            print("amount deposited successfully",self._balance)
    def withdrawl(self,amount):
        if amount<=self._balance:
            self._balance-=amount
            print("withdrawl successfull",self._balance)

a=ATM("mikey",2003,7000)
print("welcome to ATM")
pin=int(input("enter your ATM pin:"))
if a.verify_pin(pin):
    while True:
        print("\n ATM menu")
        print("1.check balance")
        print("2.cash deposit")
        print("3.amount withdrawl")
        print("4.exit")

        choice=int(input("enter your choice(1-4):"))

        if choice == 1:
            a.check_balance()
        elif choice == 2:
            amount = int(input("Enter amount to deposit: "))
            a.deposit(amount)
        elif choice == 3:
            amount = int(input("Enter amount to withdrawl: "))
            a.withdrawl(amount)
        elif choice == 4:
            print("Thank you for using our ATM")
            break
        else:
            print("Invalid choice")
else:
    print("Incorrect pin, please try again")

In [36]:
with open("encapsulation.py",'r') as code:
    program=code.read
    print(program)

<built-in method read of _io.TextIOWrapper object at 0x000001A1678D9D20>

In [43]:
print(a.dtype)
print(a.max())
print(a.min())

int64
30
1

In [44]:
import pandas as pd
import numpy as np
data= {
    "Name": ["Ravi", "Sita", "Arjun", "Ravi", "Meena"],
    "Age": [20, 21,np.nan, 20, 22],
    "Gender": ["Male", "Female", "Male", "Male", "female"],
    "Marks": [85, 90, 78, 85, np.nan],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Hyderabad", "delhi"]
}
df=pd.DataFrame(data)
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun   NaN    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  female    NaN      delhi

In [6]:
print(df.isnull())

    Name    Age  Gender  Marks   City
0  False  False   False  False  False
1  False  False   False  False  False
2  False   True   False  False  False
3  False  False   False  False  False
4  False  False   False   True  False

In [9]:
print(df.duplicated())

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [13]:
print(df.head(1))

   Name   Age Gender  Marks       City
0  Ravi  20.0   Male   85.0  Hyderabad

In [12]:
print(df.tail(3))

    Name   Age  Gender  Marks       City
2  Arjun   NaN    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  female    NaN      delhi

In [14]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     4 non-null      float64
 2   Gender  5 non-null      object
 3   Marks   4 non-null      float64
 4   City    5 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes
None

In [15]:
print(df.describe())

             Age      Marks
count   4.000000   4.000000
mean   20.750000  84.500000
std     0.957427   4.932883
min    20.000000  78.000000
25%    20.000000  83.250000
50%    20.500000  85.000000
75%    21.250000  86.250000
max    22.000000  90.000000

In [16]:
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun   NaN    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  female    NaN      delhi

In [17]:
print(df.fillna(0))

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun   0.0    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  female    0.0      delhi

In [20]:
df.loc[[2,4],["Age","Marks"]]=[[23,78],[22,93]]
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  23.0    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  female   93.0      delhi

In [26]:
df["Gender"]=df["Gender"].str.title()
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  23.0    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  Female   93.0      delhi

In [28]:
df["City"]=df["City"].str.title()
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  23.0    Male   78.0     Mumbai
3   Ravi  20.0    Male   85.0  Hyderabad
4  Meena  22.0  Female   93.0      Delhi

In [32]:
df.drop_duplicates(inplace=True)
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  23.0    Male   78.0     Mumbai
4  Meena  22.0  Female   93.0      Delhi

In [33]:
print(df)

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  23.0    Male   78.0     Mumbai
4  Meena  22.0  Female   93.0      Delhi

In [3]:
import pandas as pd
import numpy as np

data = {
        "Name": ["Ravi", "Sita", "Arjun", "Meena", "Kiran", 
                "Anita", "Rahul", "Priya", "Vikram", "Neha"],
        "Age": [20, 21, np.nan, 22, 23, 
                24, np.nan, 22, 21, 25],
        "Gender": ["Male", "Female", "Male", "Female", "Male", 
                "Female", "Male", "Female", "Male", "Female"],
        "Marks": [85, 90, 78, np.nan, 88, 
                92, 80, 95, np.nan, 89],
        "City": ["Hyderabad", "Delhi", "Mumbai", "Delhi", "Chennai", 
                "Bangalore", "Hyderabad", "Delhi", "Mumbai", "Chennai"]
}

df = pd.DataFrame(data)
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun   NaN    Male   78.0     Mumbai
3   Meena  22.0  Female    NaN      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul   NaN    Male   80.0  Hyderabad
7   Priya  22.0  Female   95.0      Delhi
8  Vikram  21.0    Male    NaN     Mumbai
9    Neha  25.0  Female   89.0    Chennai

In [4]:
print(df.isnull())

    Name    Age  Gender  Marks   City
0  False  False   False  False  False
1  False  False   False  False  False
2  False   True   False  False  False
3  False  False   False   True  False
4  False  False   False  False  False
5  False  False   False  False  False
6  False   True   False  False  False
7  False  False   False  False  False
8  False  False   False   True  False
9  False  False   False  False  False

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     8 non-null      float64
 2   Gender  10 non-null     object
 3   Marks   8 non-null      float64
 4   City    10 non-null     object
dtypes: float64(2), object(3)
memory usage: 532.0+ bytes
None

In [38]:
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun   NaN    Male   78.0     Mumbai
3   Meena  22.0  Female    NaN      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul   NaN    Male   80.0  Hyderabad
7   Priya  22.0  Female   95.0      Delhi
8  Vikram  21.0    Male    NaN     Mumbai
9    Neha  25.0  Female   89.0    Chennai

In [7]:
df.loc[[2,3,6,8],["Age","Marks"]]=[[22,78],[22,93],[23,80],[21,67]]
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun  22.0    Male   78.0     Mumbai
3   Meena  22.0  Female   93.0      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul  23.0    Male   80.0  Hyderabad
7   Priya  21.0  Female   95.0      Delhi
8  Vikram  21.0    Male   67.0     Mumbai
9    Neha  23.0  Female   89.0    Chennai

In [8]:
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun  22.0    Male   78.0     Mumbai
3   Meena  22.0  Female   93.0      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul  23.0    Male   80.0  Hyderabad
7   Priya  21.0  Female   95.0      Delhi
8  Vikram  21.0    Male   67.0     Mumbai
9    Neha  23.0  Female   89.0    Chennai

In [9]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [10]:
df["Age"].replace(25,23,inplace=True)

In [11]:
df["Age"].replace(22,21,inplace=True)
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun  21.0    Male   78.0     Mumbai
3   Meena  21.0  Female   93.0      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul  23.0    Male   80.0  Hyderabad
7   Priya  21.0  Female   95.0      Delhi
8  Vikram  21.0    Male   67.0     Mumbai
9    Neha  23.0  Female   89.0    Chennai

In [12]:
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun  21.0    Male   78.0     Mumbai
3   Meena  21.0  Female   93.0      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul  23.0    Male   80.0  Hyderabad
7   Priya  21.0  Female   95.0      Delhi
8  Vikram  21.0    Male   67.0     Mumbai
9    Neha  23.0  Female   89.0    Chennai

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     float64
 2   Gender  10 non-null     object
 3   Marks   10 non-null     float64
 4   City    10 non-null     object
dtypes: float64(2), object(3)
memory usage: 532.0+ bytes
None

In [14]:
print(df.describe())

             Age     Marks
count  10.000000  10.00000
mean   21.800000  85.70000
std     1.316561   8.53815
min    20.000000  67.00000
25%    21.000000  81.25000
50%    21.000000  88.50000
75%    23.000000  91.50000
max    24.000000  95.00000

In [6]:
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun   NaN    Male   78.0     Mumbai
3   Meena  22.0  Female    NaN      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul   NaN    Male   80.0  Hyderabad
7   Priya  22.0  Female   95.0      Delhi
8  Vikram  21.0    Male    NaN     Mumbai
9    Neha  25.0  Female   89.0    Chennai

In [7]:
print(df.head())

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun   NaN    Male   78.0     Mumbai
3  Meena  22.0  Female    NaN      Delhi
4  Kiran  23.0    Male   88.0    Chennai

In [44]:
df.iloc[:,[0,3]],df.iloc[2]

(     Name  Marks
 0    Ravi   85.0
 1    Sita   90.0
 2   Arjun   78.0
 3   Meena    NaN
 4   Kiran   88.0
 5   Anita   92.0
 6   Rahul   80.0
 7   Priya   95.0
 8  Vikram    NaN
 9    Neha   89.0,
 Name       Arjun
 Age          NaN
 Gender      Male
 Marks       78.0
 City      Mumbai
 Name: 2, dtype: object)

In [57]:
df.describe()
df["Age"].fillna(22,inplace=True)
df.dropna(subset=["Marks"])

    Name   Age  Gender  Marks       City
0   Ravi  20.0    Male   85.0  Hyderabad
1   Sita  21.0  Female   90.0      Delhi
2  Arjun  22.0    Male   78.0     Mumbai
4  Kiran  23.0    Male   88.0    Chennai
5  Anita  24.0  Female   92.0  Bangalore
6  Rahul  22.0    Male   80.0  Hyderabad
7  Priya  22.0  Female   95.0      Delhi
9   Neha  25.0  Female   89.0    Chennai

In [58]:
print(df)

     Name   Age  Gender  Marks       City
0    Ravi  20.0    Male   85.0  Hyderabad
1    Sita  21.0  Female   90.0      Delhi
2   Arjun  22.0    Male   78.0     Mumbai
3   Meena  22.0  Female    NaN      Delhi
4   Kiran  23.0    Male   88.0    Chennai
5   Anita  24.0  Female   92.0  Bangalore
6   Rahul  22.0    Male   80.0  Hyderabad
7   Priya  22.0  Female   95.0      Delhi
8  Vikram  21.0    Male    NaN     Mumbai
9    Neha  25.0  Female   89.0    Chennai

In [71]:
df.groupby("City").mean("Marks"),df["Gender"].value_counts()

(                 Age  Marks
 City
 Bangalore  24.000000   92.0
 Chennai    24.000000   88.5
 Delhi      21.666667   92.5
 Hyderabad  21.000000   82.5
 Mumbai     21.500000   78.0,
 Gender
 Male      5
 Female    5
 Name: count, dtype: int64)

In [66]:
a=89
b=88
c=a+b
c
d=c/2
d

88.5

In [84]:
pd.pivot_table(df,values="Marks",columns=['Gender','City'],aggfunc="mean")

Gender    Female                  Male
City   Bangalore Chennai Delhi Chennai Hyderabad Mumbai
Marks       92.0    89.0  92.5    88.0      82.5   78.0

In [87]:
df.sort_values("Marks",ascending=False),df['Marks'].rank()

(     Name   Age  Gender  Marks       City
 7   Priya  22.0  Female   95.0      Delhi
 5   Anita  24.0  Female   92.0  Bangalore
 1    Sita  21.0  Female   90.0      Delhi
 9    Neha  25.0  Female   89.0    Chennai
 4   Kiran  23.0    Male   88.0    Chennai
 0    Ravi  20.0    Male   85.0  Hyderabad
 6   Rahul  22.0    Male   80.0  Hyderabad
 2   Arjun  22.0    Male   78.0     Mumbai
 3   Meena  22.0  Female    NaN      Delhi
 8  Vikram  21.0    Male    NaN     Mumbai,
 0    3.0
 1    6.0
 2    1.0
 3    NaN
 4    4.0
 5    7.0
 6    2.0
 7    8.0
 8    NaN
 9    5.0
 Name: Marks, dtype: float64)

In [95]:
print(df['Marks'].max(),df["Marks"].min(),df["Marks"].mean(),df["Marks"].median(),df['Marks'].std())

95.0 78.0 87.125 88.5 5.817154434453817

In [96]:
print(type(lambda x: x))

<class 'function'>

In [101]:
print(bool(""))

False

In [ ]:
x=[1,2,3]
print(list(map(lambda x: x*2)))

TypeError: map() must have at least two arguments.

In [106]:
print(type({}))

<class 'dict'>

In [107]:
print(0.1+0.2==0.3)

False

In [108]:
print(bool("False"))

True